# Generated by Django 4.0.2 on 2022-04-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='observacao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='quantidade',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('ACOUGUE', 'Açougue'), ('BEBIDAS', 'Bebidas'), ('CEREAIS', 'Cereais'), ('COZINHA', 'Cozinha'), ('HORTIFRUTI', 'Hortifruti'), ('LACTICINIOS', 'Lacticínios'), ('LIMPEZA', 'Limpeza'), ('TEMPEROS', 'Temperos'), ('UTENCILIOS', 'Utensílios')], max_length=50),
        ),
    ]
