# Generated by Django 4.0.2 on 2022-04-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0002_produto_quantidade_alter_movimentacao_observacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
